columns_keep = [
  # 'Community Name',
  # 'Region',
  # 'Map reference',
  # 'Grid reference',
  'Location',
  # 'Population Density',
  'Travel time to GPO (minutes)',
  # 'Distance to GPO (km)',
  'LGA',
  # 'Primary Care Partnership',
  # 'Medicare Local',
  'Area (km^2)',
  'ARIA+ (min)',
  'ARIA+ (max)',
  'ARIA+ (avg)',
  'ABS remoteness category',
  # 'DHS Area',
  'Commercial (km^2)',
  # 'Commercial (%)',
  'Industrial (km^2)',
  # 'Industrial (%)',
  'Residential (km^2)',
  # 'Residential (%)',
  'Rural (km^2)',
  # 'Rural (%)',
  'Other (km^2)',
  # 'Other (%)',
  # '2012 ERP age 0-4, persons',
  # '2012 ERP age 0-4, %',
  # '2012 ERP age 5-9, persons',
  # '2012 ERP age 5-9, %',
  # '2012 ERP age 10-14, persons',
  # '2012 ERP age 10-14, %',
  # '2012 ERP age 15-19, persons',
  # '2012 ERP age 15-19, %',
  # '2012 ERP age 20-24, persons',
  # '2012 ERP age 20-24, %',
  # '2012 ERP age 25-44, persons',
  # '2012 ERP age 25-44, %',
  # '2012 ERP age 45-64, persons',
  # '2012 ERP age 45-64, %',
  # '2012 ERP age 65-69, persons',
  # '2012 ERP age 65-69, %',
  # '2012 ERP age 70-74, persons',
  # '2012 ERP age 70-74, %',
  # '2012 ERP age 75-79, persons',
  # '2012 ERP age 75-79, %',
  # '2012 ERP age 80-84, persons',
  # '2012 ERP age 80-84, %',
  # '2012 ERP age 85+, persons',
  # '2012 ERP age 85+, %',
  '2012 ERP, total',
  # '2007 ERP age 0-4, persons',
  # '2007 ERP age 0-4, %',
  # '2007 ERP age 5-9, persons',
  # '2007 ERP age 5-9, %',
  # '2007 ERP age 10-14, persons',
  # '2007 ERP age 10-14, %',
  # '2007 ERP age 15-19, persons',
  # '2007 ERP age 15-19, %',
  # '2007 ERP age 20-24, persons',
  # '2007 ERP age 20-24, %',
  # '2007 ERP age 25-44, persons',
  # '2007 ERP age 25-44, %',
  # '2007 ERP age 45-64, persons',
  # '2007 ERP age 45-64, %',
  # '2007 ERP age 65-69, persons',
  # '2007 ERP age 65-69, %',
  # '2007 ERP age 70-74, persons',
  # '2007 ERP age 70-74, %',
  # '2007 ERP age 75-79, persons',
  # '2007 ERP age 75-79, %',
  # '2007 ERP age 80-84, persons',
  # '2007 ERP age 80-84, %',
  # '2007 ERP age 85+, persons',
  # '2007 ERP age 85+, %',
  '2007 ERP, total',
  # '% change, 2007-2012, age 0-4',
  # '% change, 2007-2012, age 5-9',
  # '% change, 2007-2012, age 10-14',
  # '% change, 2007-2012, age 15-19',
  # '% change, 2007-2012, age 20-24',
  # '% change, 2007-2012, age 25-44',
  # '% change, 2007-2012, age 45-64',
  # '% change, 2007-2012, age 65-69',
  # '% change, 2007-2012, age 70-74',
  # '% change, 2007-2012, age 75-79',
  # '% change, 2007-2012, age 80-84',
  # '% change, 2007-2012, age 85+',
  # '% change, 2007-2012, total',
  'Public Hospitals',
  'Private Hospitals',
  'Community Health Centres',
  'Bush Nursing Centres',
  'Allied Health',
  'Alternative Health',
  'Child Protection and Family',
  'Dental',
  'Disability',
  'General Practice',
  'Homelessness',
  'Mental Health',
  'Pharmacies',
  'Aged Care (High Care)',
  'Aged Care (Low Care)',
  'Aged Care (SRS)',
  'Kinder and/or Childcare',
  'Primary Schools',
  'Secondary Schools',
  'P12 Schools',
  'Other Schools',
  'Centrelink Offices',
  'Medicare Offices',
  'Medicare Access Points',
  'Number of Households',
  # 'Average persons per household',
  'Occupied private dwellings',
  # 'Occupied private dwellings, %',
  'Population in non-private dwellings',
  'Public Housing Dwellings',
  # '% dwellings which are public housing',
  'Dwellings with no motor vehicle',
  # 'Dwellings with no motor vehicle, %',
  'Dwellings with no internet',
  # 'Dwellings with no internet, %',
  'Equivalent household income <$600/week',
  # 'Equivalent household income <$600/week, %',
  'Personal income <$400/week, persons',
  # 'Personal income <$400/week, %',
  'Number of families',
  'Female-headed lone parent families',
  # 'Female-headed lone parent families, %',
  'Male-headed lone parent families',
  # 'Male-headed lone parent families, %',
  '% residing near PT',
  'IRSD (min)',
  'IRSD (max)',
  'IRSD (avg)',
  'Primary school students',
  'Secondary school students',
  'TAFE students',
  'University students',
  'Holds degree or higher, persons',
  # 'Holds degree or higher, %',
  'Did not complete year 12, persons',
  # 'Did not complete year 12, %',
  'Unemployed, persons',
  # 'Unemployed, %',
  'Volunteers, persons',
  # 'Volunteers, %',
  'Requires assistance with core activities, persons',
  # 'Requires assistance with core activities, %',
  'Aged 75+ and lives alone, persons',
  # 'Aged 75+ and lives alone, %',
  'Unpaid carer to person with disability, persons',
  # 'Unpaid carer to person with disability, %',
  'Unpaid carer of children, persons',
  # 'Unpaid carer of children, %',
  # 'Top industry',
  # 'Top industry, %',
  # '2nd top industry - persons',
  # '2nd top industry, %',
  # '3rd top industry - persons',
  # '3rd top industry, %',
  # 'Top occupation',
  # 'Top occupation, %',
  # '2nd top occupation - persons',
  # '2nd top occupation, %',
  # '3rd top occupation - persons',
  # '3rd top occupation, %',
  'Aboriginal or Torres Strait Islander, persons',
  # 'Aboriginal or Torres Strait Islander, %',
  'Born overseas, persons',
  # 'Born overseas, %',
  'Born in non-English speaking country, persons',
  # 'Born in non-English speaking country, %',
  'Speaks LOTE at home, persons',
  # 'Speaks LOTE at home, %',
  'Poor English proficiency, persons',
  # 'Poor English proficiency, %',
  # 'Top country of birth',
  # 'Top country of birth, persons',
  # 'Top country of birth, %',
  # '2nd top country of birth',
  # '2nd top country of birth, persons',
  # '2nd top country of birth, %',
  # '3rd top country of birth',
  # '3rd top country of birth, persons',
  # '3rd top country of birth, %',
  # '4th top country of birth',
  # '4th top country of birth, persons',
  # '4th top country of birth, %',
  # '5th top country of birth',
  # '5th top country of birth, persons',
  # '5th top country of birth, %',
  # 'Top language spoken',
  # 'Top language spoken, persons',
  # 'Top language spoken, %',
  # '2nd top language spoken',
  # '2nd top language spoken, persons',
  # '2nd top language spoken, %',
  # '3rd top language spoken',
  # '3rd top language spoken, persons',
  # '3rd top language spoken, %',
  # '4th top language spoken',
  # '4th top language spoken, persons',
  # '4th top language spoken, %',
  # '5th top language spoken',
  # '5th top language spoken, persons',
  # '5th top language spoken, %',
  # 'Public hospital separations, 2012-13',
  # 'Nearest Public Hospital',
  'Travel time to nearest public hospital',
  # 'Distance to nearest public hospital',
  # 'Obstetric type separations, 2012-13',
  # 'Nearest public hospital with maternity services',
  'Time to nearest public hospital with maternity services',
  # 'Distance to nearest public hospital with maternity services',
  'Presentations to emergency departments, 2012-13',
  # 'Nearest public hospital with emergency department',
  # 'Travel time to nearest public hospital with emergency department',
  'Distance to nearest public hospital with emergency department',
  'Presentations to emergency departments due to injury',
  # 'Presentations to emergency departments due to injury, %',
  'Category 4 & 5 emergency department presentations',
  # 'Category 4 & 5 emergency department presentations, %'
]

columns_derive = [
  # 'Community Name',
  # 'Region',
  # 'Map reference',
  # 'Grid reference',
  # 'Location',
  # 'Population Density',
  # 'Travel time to GPO (minutes)',
  # 'Distance to GPO (km)',
  # 'LGA',
  # 'Primary Care Partnership',
  # 'Medicare Local',
  # 'Area (km^2)',
  # 'ARIA+ (min)',
  # 'ARIA+ (max)',
  # 'ARIA+ (avg)',
  # 'ABS remoteness category',
  # 'DHS Area',
  # 'Commercial (km^2)',
  'Commercial (%)',
  # 'Industrial (km^2)',
  'Industrial (%)',
  # 'Residential (km^2)',
  'Residential (%)',
  # 'Rural (km^2)',
  'Rural (%)',
  # 'Other (km^2)',
  'Other (%)',
  # '2012 ERP age 0-4, persons',
  # '2012 ERP age 0-4, %',
  # '2012 ERP age 5-9, persons',
  # '2012 ERP age 5-9, %',
  # '2012 ERP age 10-14, persons',
  # '2012 ERP age 10-14, %',
  # '2012 ERP age 15-19, persons',
  # '2012 ERP age 15-19, %',
  # '2012 ERP age 20-24, persons',
  # '2012 ERP age 20-24, %',
  # '2012 ERP age 25-44, persons',
  # '2012 ERP age 25-44, %',
  # '2012 ERP age 45-64, persons',
  # '2012 ERP age 45-64, %',
  # '2012 ERP age 65-69, persons',
  # '2012 ERP age 65-69, %',
  # '2012 ERP age 70-74, persons',
  # '2012 ERP age 70-74, %',
  # '2012 ERP age 75-79, persons',
  # '2012 ERP age 75-79, %',
  # '2012 ERP age 80-84, persons',
  # '2012 ERP age 80-84, %',
  # '2012 ERP age 85+, persons',
  # '2012 ERP age 85+, %',
  # '2012 ERP, total',
  # '2007 ERP age 0-4, persons',
  # '2007 ERP age 0-4, %',
  # '2007 ERP age 5-9, persons',
  # '2007 ERP age 5-9, %',
  # '2007 ERP age 10-14, persons',
  # '2007 ERP age 10-14, %',
  # '2007 ERP age 15-19, persons',
  # '2007 ERP age 15-19, %',
  # '2007 ERP age 20-24, persons',
  # '2007 ERP age 20-24, %',
  # '2007 ERP age 25-44, persons',
  # '2007 ERP age 25-44, %',
  # '2007 ERP age 45-64, persons',
  # '2007 ERP age 45-64, %',
  # '2007 ERP age 65-69, persons',
  # '2007 ERP age 65-69, %',
  # '2007 ERP age 70-74, persons',
  # '2007 ERP age 70-74, %',
  # '2007 ERP age 75-79, persons',
  # '2007 ERP age 75-79, %',
  # '2007 ERP age 80-84, persons',
  # '2007 ERP age 80-84, %',
  # '2007 ERP age 85+, persons',
  # '2007 ERP age 85+, %',
  # '2007 ERP, total',
  # '% change, 2007-2012, age 0-4',
  # '% change, 2007-2012, age 5-9',
  # '% change, 2007-2012, age 10-14',
  # '% change, 2007-2012, age 15-19',
  # '% change, 2007-2012, age 20-24',
  # '% change, 2007-2012, age 25-44',
  # '% change, 2007-2012, age 45-64',
  # '% change, 2007-2012, age 65-69',
  # '% change, 2007-2012, age 70-74',
  # '% change, 2007-2012, age 75-79',
  # '% change, 2007-2012, age 80-84',
  # '% change, 2007-2012, age 85+',
  # '% change, 2007-2012, total',
  # 'Public Hospitals',
  # 'Private Hospitals',
  # 'Community Health Centres',
  # 'Bush Nursing Centres',
  # 'Allied Health',
  # 'Alternative Health',
  # 'Child Protection and Family',
  # 'Dental',
  # 'Disability',
  # 'General Practice',
  # 'Homelessness',
  # 'Mental Health',
  # 'Pharmacies',
  # 'Aged Care (High Care)',
  # 'Aged Care (Low Care)',
  # 'Aged Care (SRS)',
  # 'Kinder and/or Childcare',
  # 'Primary Schools',
  # 'Secondary Schools',
  # 'P12 Schools',
  # 'Other Schools',
  # 'Centrelink Offices',
  # 'Medicare Offices',
  # 'Medicare Access Points',
  # 'Number of Households',
  'Average persons per household',
  # 'Occupied private dwellings',
  'Occupied private dwellings, %',
  # 'Population in non-private dwellings',
  # 'Public Housing Dwellings',
  '% dwellings which are public housing',
  # 'Dwellings with no motor vehicle',
  'Dwellings with no motor vehicle, %',
  # 'Dwellings with no internet',
  'Dwellings with no internet, %',
  # 'Equivalent household income <$600/week',
  'Equivalent household income <$600/week, %',
  # 'Personal income <$400/week, persons',
  'Personal income <$400/week, %',
  # 'Number of families',
  # 'Female-headed lone parent families',
  'Female-headed lone parent families, %',
  # 'Male-headed lone parent families',
  'Male-headed lone parent families, %',
  # '% residing near PT',
  # 'IRSD (min)',
  # 'IRSD (max)',
  # 'IRSD (avg)',
  # 'Primary school students',
  # 'Secondary school students',
  # 'TAFE students',
  # 'University students',
  # 'Holds degree or higher, persons',
  'Holds degree or higher, %',
  # 'Did not complete year 12, persons',
  'Did not complete year 12, %',
  # 'Unemployed, persons',
  'Unemployed, %',
  # 'Volunteers, persons',
  'Volunteers, %',
  # 'Requires assistance with core activities, persons',
  'Requires assistance with core activities, %',
  # 'Aged 75+ and lives alone, persons',
  'Aged 75+ and lives alone, %',
  # 'Unpaid carer to person with disability, persons',
  'Unpaid carer to person with disability, %',
  # 'Unpaid carer of children, persons',
  'Unpaid carer of children, %',
  # 'Top industry',
  # 'Top industry, %',
  # '2nd top industry - persons',
  # '2nd top industry, %',
  # '3rd top industry - persons',
  # '3rd top industry, %',
  # 'Top occupation',
  # 'Top occupation, %',
  # '2nd top occupation - persons',
  # '2nd top occupation, %',
  # '3rd top occupation - persons',
  # '3rd top occupation, %',
  # 'Aboriginal or Torres Strait Islander, persons',
  'Aboriginal or Torres Strait Islander, %',
  # 'Born overseas, persons',
  'Born overseas, %',
  # 'Born in non-English speaking country, persons',
  'Born in non-English speaking country, %',
  # 'Speaks LOTE at home, persons',
  # 'Speaks LOTE at home, %',
  # 'Poor English proficiency, persons',
  # 'Poor English proficiency, %',
  # 'Top country of birth',
  # 'Top country of birth, persons',
  # 'Top country of birth, %',
  # '2nd top country of birth',
  # '2nd top country of birth, persons',
  # '2nd top country of birth, %',
  # '3rd top country of birth',
  # '3rd top country of birth, persons',
  # '3rd top country of birth, %',
  # '4th top country of birth',
  # '4th top country of birth, persons',
  # '4th top country of birth, %',
  # '5th top country of birth',
  # '5th top country of birth, persons',
  # '5th top country of birth, %',
  # 'Top language spoken',
  # 'Top language spoken, persons',
  # 'Top language spoken, %',
  # '2nd top language spoken',
  # '2nd top language spoken, persons',
  # '2nd top language spoken, %',
  # '3rd top language spoken',
  # '3rd top language spoken, persons',
  # '3rd top language spoken, %',
  # '4th top language spoken',
  # '4th top language spoken, persons',
  # '4th top language spoken, %',
  # '5th top language spoken',
  # '5th top language spoken, persons',
  # '5th top language spoken, %',
  # 'Public hospital separations, 2012-13',
  # 'Nearest Public Hospital',
  # 'Travel time to nearest public hospital',
  # 'Distance to nearest public hospital',
  # 'Obstetric type separations, 2012-13',
  # 'Nearest public hospital with maternity services',
  # 'Time to nearest public hospital with maternity services',
  # 'Distance to nearest public hospital with maternity services',
  # 'Presentations to emergency departments, 2012-13',
  # 'Nearest public hospital with emergency department',
  # 'Travel time to nearest public hospital with emergency department',
  # 'Distance to nearest public hospital with emergency department',
  # 'Presentations to emergency departments due to injury',
  'Presentations to emergency departments due to injury, %',
  # 'Category 4 & 5 emergency department presentations',
  'Category 4 & 5 emergency department presentations, %'
]